/* Generated by Yosys 0.53 (git sha1 53c22ab7c, ccache clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
/* verilator lint_off CASEOVERLAP*/
module FP2IEEE_H0(clk, rst, X, R);
  wire _00_;
  wire [9:0] _01_;
  wire _02_;
  wire _03_;
  wire [9:0] _04_;
  wire _05_;
  wire [9:0] _06_;
  wire _07_;
  wire [4:0] _08_;
  wire _09_;
  wire [4:0] _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  output [15:0] R;
  wire [15:0] R;
  input [17:0] X;
  wire [17:0] X;
  input clk;
  wire clk;
  wire [1:0] exnx;
  wire [4:0] expr;
  wire [4:0] expx;
  wire expzero;
  wire [9:0] fracr;
  wire [9:0] fracx;
  input rst;
  wire rst;
  wire sx;
  assign _13_ = exnx == 2'h0;
  assign _14_ = _12_ | _13_;
  assign _15_ = _14_ ? X[15] : 1'h0;
  assign _16_ = expx == 5'h00;
  assign _17_ = _16_ ? 1'h1 : 1'h0;
  assign _18_ = exnx == 2'h0;
  assign _01_ = _18_ ? 10'h000 : _04_;
  assign _02_ = exnx == 2'h1;
  assign _03_ = _02_ & expzero;
  assign _04_ = _03_ ? { 1'h1, fracx[9:1] } : _06_;
  assign _05_ = exnx == 2'h1;
  assign _06_ = _05_ ? fracx : { 9'h000, exnx[0] };
  assign _07_ = exnx == 2'h0;
  assign _08_ = _07_ ? 5'h00 : _10_;
  assign _09_ = exnx == 2'h1;
  assign _10_ = _09_ ? expx : 5'h1f;
  assign _00_ = exnx == 2'h1;
  assign _11_ = exnx == 2'h2;
  assign _12_ = _00_ | _11_;
  assign fracx = X[9:0];
  assign exnx = X[17:16];
  assign expx = X[14:10];
  assign sx = _15_;
  assign expzero = _17_;
  assign fracr = _01_;
  assign expr = _08_;
  assign R = { sx, expr, fracr };
endmodule
/* verilator lint_on CASEOVERLAP*/
