/* Generated by Yosys 0.53 (git sha1 53c22ab7c, ccache clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
/* verilator lint_off CASEOVERLAP*/
module FP2Fix_H0(clk, rst, X, R, ov);
  wire _00_;
  wire [3:0] _01_;
  wire _02_;
  wire _03_;
  wire [15:0] _04_;
  wire _05_;
  wire [15:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [11:0] _14_;
  wire [11:0] _15_;
  wire [5:0] _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  output [15:0] R;
  wire [15:0] R;
  input [17:0] X;
  wire [17:0] X;
  wire [11:0] bigzero;
  input clk;
  wire clk;
  wire [1:0] exn;
  wire [4:0] exponentfield;
  wire [15:0] fixedpointval;
  wire [15:0] \fxp_shifter:47 ;
  wire infnan;
  wire [10:0] mantissa;
  wire minustwotomsb;
  wire [11:0] \negadder:25 ;
  output ov;
  wire ov;
  wire overflow;
  input rst;
  wire rst;
  wire [5:0] shiftval;
  wire [3:0] shiftvalshort;
  wire sign;
  wire [11:0] signedmantissa;
  wire underflow;
  wire [11:0] xoredmantissa;
  wire zero;
  assign _13_ = exn[1] ? 1'h1 : 1'h0;
  assign _14_ = { sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign } ^ { 1'h0, mantissa };
  assign _16_ = 6'h1d - { 1'h0, exponentfield };
  assign _17_ = $signed(shiftval) > $signed(6'h0f);
  assign _18_ = _17_ ? 1'h1 : 1'h0;
  assign _19_ = underflow | zero;
  assign _01_ = _19_ ? 4'hf : shiftval[3:0];
  assign _02_ = X == 18'h1f800;
  assign _03_ = _02_ ? 1'h1 : 1'h0;
  assign _05_ = zero | minustwotomsb;
  assign _06_ = _05_ ? { minustwotomsb, 15'h0000 } : fixedpointval;
  assign _07_ = ~ zero;
  assign _08_ = infnan | overflow;
  assign _09_ = _07_ & _08_;
  assign _10_ = ~ minustwotomsb;
  assign _12_ = _09_ & _10_;
  assign _00_ = exn == 2'h0;
  assign _11_ = _00_ ? 1'h1 : 1'h0;
  rightshifter12_by_max_15_freq300_uid6_FP2Fix_H0 fxp_shifter (
    .clk(clk),
    .padbit(sign),
    .r(_04_),
    .rst(rst),
    .s(shiftvalshort),
    .x(signedmantissa)
  );
  intadder_12_freq300_uid4_FP2Fix_H0 negadder (
    .cin(sign),
    .clk(clk),
    .r(_15_),
    .rst(rst),
    .x(xoredmantissa),
    .y(bigzero)
  );
  assign exn = X[17:16];
  assign sign = X[15];
  assign exponentfield = X[14:10];
  assign zero = _11_;
  assign infnan = _13_;
  assign mantissa = { 1'h1, X[9:0] };
  assign xoredmantissa = _14_;
  assign bigzero = 12'h000;
  assign signedmantissa = \negadder:25 ;
  assign shiftval = _16_;
  assign overflow = shiftval[5];
  assign underflow = _18_;
  assign shiftvalshort = _01_;
  assign minustwotomsb = _03_;
  assign fixedpointval = \fxp_shifter:47 ;
  assign \negadder:25  = _15_;
  assign \fxp_shifter:47  = _04_;
  assign R = _06_;
  assign ov = _12_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module intadder_12_freq300_uid4_FP2Fix_H0(clk, rst, x, y, cin, r);
  wire [11:0] _0_;
  wire [11:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [11:0] r;
  wire [11:0] r;
  input rst;
  wire rst;
  wire [11:0] rtmp;
  input [11:0] x;
  wire [11:0] x;
  input [11:0] y;
  wire [11:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 11'h000, cin };
  assign rtmp = _1_;
  assign r = rtmp;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module rightshifter12_by_max_15_freq300_uid6_FP2Fix_H0(clk, rst, x, s, padbit, r);
  wire [12:0] _0_;
  wire [14:0] _1_;
  wire [18:0] _2_;
  wire [26:0] _3_;
  input clk;
  wire clk;
  wire [11:0] level0;
  wire [12:0] level1;
  wire [14:0] level2;
  wire [18:0] level3;
  wire [26:0] level4;
  input padbit;
  wire padbit;
  wire [3:0] ps;
  output [15:0] r;
  wire [15:0] r;
  input rst;
  wire rst;
  input [3:0] s;
  wire [3:0] s;
  input [11:0] x;
  wire [11:0] x;
  assign _0_ = ps[0] ? { padbit, level0 } : { level0, 1'h0 };
  assign _1_ = ps[1] ? { padbit, padbit, level1 } : { level1, 2'h0 };
  assign _2_ = ps[2] ? { padbit, padbit, padbit, padbit, level2 } : { level2, 4'h0 };
  assign _3_ = ps[3] ? { padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, level3 } : { level3, 8'h00 };
  assign ps = s;
  assign level0 = x;
  assign level1 = _0_;
  assign level2 = _1_;
  assign level3 = _2_;
  assign level4 = _3_;
  assign r = level4[26:11];
endmodule
/* verilator lint_on CASEOVERLAP*/
