/* Generated by Yosys 0.53 (git sha1 53c22ab7c, ccache clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
/* verilator lint_off CASEOVERLAP*/
module FP2Fix_S0(clk, rst, X, R, ov);
  wire _00_;
  wire [4:0] _01_;
  wire _02_;
  wire _03_;
  wire [31:0] _04_;
  wire _05_;
  wire [31:0] _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire [24:0] _14_;
  wire [24:0] _15_;
  wire [8:0] _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  output [31:0] R;
  wire [31:0] R;
  input [33:0] X;
  wire [33:0] X;
  wire [24:0] bigzero;
  input clk;
  wire clk;
  wire [1:0] exn;
  wire [7:0] exponentfield;
  wire [31:0] fixedpointval;
  wire [31:0] \fxp_shifter:52 ;
  wire infnan;
  wire [23:0] mantissa;
  wire minustwotomsb;
  wire [24:0] \negadder:30 ;
  output ov;
  wire ov;
  wire overflow;
  input rst;
  wire rst;
  wire [8:0] shiftval;
  wire [4:0] shiftvalshort;
  wire sign;
  wire [24:0] signedmantissa;
  wire underflow;
  wire [24:0] xoredmantissa;
  wire zero;
  assign _13_ = exn[1] ? 1'h1 : 1'h0;
  assign _14_ = { sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign, sign } ^ { 1'h0, mantissa };
  assign _16_ = 9'h09d - { 1'h0, exponentfield };
  assign _17_ = $signed(shiftval) > $signed(9'h01f);
  assign _18_ = _17_ ? 1'h1 : 1'h0;
  assign _19_ = underflow | zero;
  assign _01_ = _19_ ? 5'h1f : shiftval[4:0];
  assign _02_ = X == 34'h1cf000000;
  assign _03_ = _02_ ? 1'h1 : 1'h0;
  assign _05_ = zero | minustwotomsb;
  assign _06_ = _05_ ? { minustwotomsb, 31'h00000000 } : fixedpointval;
  assign _07_ = ~ zero;
  assign _08_ = infnan | overflow;
  assign _09_ = _07_ & _08_;
  assign _10_ = ~ minustwotomsb;
  assign _12_ = _09_ & _10_;
  assign _00_ = exn == 2'h0;
  assign _11_ = _00_ ? 1'h1 : 1'h0;
  rightshifter25_by_max_31_freq250_uid6_FP2Fix_S0 fxp_shifter (
    .clk(clk),
    .padbit(sign),
    .r(_04_),
    .rst(rst),
    .s(shiftvalshort),
    .x(signedmantissa)
  );
  intadder_25_freq250_uid4_FP2Fix_S0 negadder (
    .cin(sign),
    .clk(clk),
    .r(_15_),
    .rst(rst),
    .x(xoredmantissa),
    .y(bigzero)
  );
  assign exn = X[33:32];
  assign sign = X[31];
  assign exponentfield = X[30:23];
  assign zero = _11_;
  assign infnan = _13_;
  assign mantissa = { 1'h1, X[22:0] };
  assign xoredmantissa = _14_;
  assign bigzero = 25'h0000000;
  assign signedmantissa = \negadder:30 ;
  assign shiftval = _16_;
  assign overflow = shiftval[8];
  assign underflow = _18_;
  assign shiftvalshort = _01_;
  assign minustwotomsb = _03_;
  assign fixedpointval = \fxp_shifter:52 ;
  assign \negadder:30  = _15_;
  assign \fxp_shifter:52  = _04_;
  assign R = _06_;
  assign ov = _12_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module intadder_25_freq250_uid4_FP2Fix_S0(clk, rst, x, y, cin, r);
  wire [24:0] _0_;
  wire [24:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [24:0] r;
  wire [24:0] r;
  input rst;
  wire rst;
  wire [24:0] rtmp;
  input [24:0] x;
  wire [24:0] x;
  input [24:0] y;
  wire [24:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 24'h000000, cin };
  assign rtmp = _1_;
  assign r = rtmp;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module rightshifter25_by_max_31_freq250_uid6_FP2Fix_S0(clk, rst, x, s, padbit, r);
  wire [25:0] _0_;
  wire [27:0] _1_;
  wire [31:0] _2_;
  wire [39:0] _3_;
  wire [55:0] _4_;
  input clk;
  wire clk;
  wire [24:0] level0;
  wire [25:0] level1;
  wire [27:0] level2;
  wire [31:0] level3;
  wire [39:0] level4;
  wire [55:0] level5;
  input padbit;
  wire padbit;
  wire [4:0] ps;
  output [31:0] r;
  wire [31:0] r;
  input rst;
  wire rst;
  input [4:0] s;
  wire [4:0] s;
  input [24:0] x;
  wire [24:0] x;
  assign _4_ = ps[4] ? { padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, level4 } : { level4, 16'h0000 };
  assign _0_ = ps[0] ? { padbit, level0 } : { level0, 1'h0 };
  assign _1_ = ps[1] ? { padbit, padbit, level1 } : { level1, 2'h0 };
  assign _2_ = ps[2] ? { padbit, padbit, padbit, padbit, level2 } : { level2, 4'h0 };
  assign _3_ = ps[3] ? { padbit, padbit, padbit, padbit, padbit, padbit, padbit, padbit, level3 } : { level3, 8'h00 };
  assign ps = s;
  assign level0 = x;
  assign level1 = _0_;
  assign level2 = _1_;
  assign level3 = _2_;
  assign level4 = _3_;
  assign level5 = _4_;
  assign r = level5[55:24];
endmodule
/* verilator lint_on CASEOVERLAP*/
