/* Generated by Yosys 0.53 (git sha1 53c22ab7c, ccache clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
/* verilator lint_off CASEOVERLAP*/
module Fix2FP_H2(clk, rst, I, O);
  wire [3:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [15:0] _04_;
  wire _05_;
  wire _06_;
  wire [15:0] _07_;
  wire [16:0] _08_;
  wire [3:0] _09_;
  wire _10_;
  wire [15:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [15:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [4:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  reg _26_;
  reg _27_;
  reg _28_;
  reg _29_;
  wire [4:0] _30_;
  wire [5:0] _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire _35_;
  input [15:0] I;
  wire [15:0] I;
  output [17:0] O;
  wire [17:0] O;
  wire [3:0] biassofones;
  wire [4:0] biasssignal;
  wire [5:0] biasssignalbit;
  input clk;
  wire clk;
  wire [15:0] concatenationforrounding;
  wire [4:0] convertedexponent;
  wire [4:0] convertedexponentafterrounding;
  wire [5:0] convertedexponentbit;
  wire [9:0] convertedfractionafterrounding;
  wire correctingexponent;
  wire [4:0] \exponentconversion:22 ;
  wire [5:0] \exponentfinal:34 ;
  wire firstbitofrest;
  wire [9:0] fractionconverted;
  wire [16:0] \fractionconverter:72 ;
  wire [3:0] fractionremainder;
  wire [15:0] \input ;
  wire [14:0] input2lzoc;
  wire lastbitoffraction;
  wire lsbselection;
  wire [3:0] \lzoc_component:11 ;
  wire [15:0] \lzoc_component:12 ;
  wire [3:0] minusone;
  wire [15:0] minusone4zd;
  wire [4:0] msb2signal;
  wire msbselection;
  wire [3:0] \onesubstracter:82 ;
  wire outputofmux1;
  wire outputofmux2;
  wire outputofmux3;
  wire overflowsignal;
  wire [4:0] partialconvertedexponent;
  wire [5:0] partialconvertedexponentbit;
  wire [15:0] passedinput;
  wire [15:0] possiblecorrector4rounding;
  wire [15:0] roundedresult;
  wire [15:0] \roundingadder:105 ;
  input rst;
  wire rst;
  wire [1:0] selection;
  wire [15:0] sign2vector;
  wire sign4ou;
  wire signsignal;
  wire signsignal_d1;
  wire signsignal_d2;
  wire [1:0] specialbits;
  wire [16:0] tempaddsign;
  wire [15:0] tempconvert;
  wire [16:0] tempconvert0;
  wire [16:0] tempfractionresult;
  wire [3:0] temporalexponent;
  wire [15:0] temporalfraction;
  wire [15:0] temppaddingaddsign;
  wire underflowsignal;
  wire [4:0] valueexponent;
  wire [15:0] \zerod:55 ;
  wire [15:0] zerods;
  wire [3:0] zerofractionresult;
  wire zeroinput;
  wire zeroinput_d1;
  wire zeroinput_d2;
  wire zeropadding4exponent;
  wire zeroremainder;
  assign _19_ = overflowsignal | roundedresult[15];
  assign _20_ = ~ zeroinput_d2;
  assign _21_ = underflowsignal & _20_;
  assign _23_ = ~ _21_;
  assign _24_ = ~ zeroinput_d2;
  assign _25_ = _24_ ? { msbselection, lsbselection } : 2'h0;
  always @(posedge clk)
    _26_ <= signsignal;
  always @(posedge clk)
    _27_ <= signsignal_d1;
  always @(posedge clk)
    _28_ <= zeroinput;
  always @(posedge clk)
    _29_ <= zeroinput_d1;
  assign _22_ = ~ { zeropadding4exponent, temporalexponent };
  assign _32_ = convertedexponentbit[5:4] == 2'h1;
  assign _33_ = _32_ & sign4ou;
  assign _34_ = _33_ ? 1'h1 : 1'h0;
  assign _35_ = ~ sign4ou;
  assign _01_ = convertedexponentbit[5:4] == 2'h2;
  assign _02_ = _01_ & _35_;
  assign _03_ = _02_ ? 1'h1 : 1'h0;
  assign _05_ = ~ signsignal;
  assign _06_ = zerods[15] & _05_;
  assign _07_ = sign2vector ^ temporalfraction;
  assign _10_ = ~ tempfractionresult[3];
  assign _12_ = _10_ & zerofractionresult[3];
  assign _13_ = ~ _12_;
  assign _14_ = zeroremainder == 1'h0;
  function [0:0] \:93 ;
    input [0:0] a;
    input [0:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:93  = b[0:0];
      default:
        \:93  = a;
    endcase
  endfunction
  assign _15_ = \:93 (1'h1, outputofmux3, _14_);
  assign _16_ = firstbitofrest == 1'h1;
  function [0:0] \:97 ;
    input [0:0] a;
    input [0:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:97  = b[0:0];
      default:
        \:97  = a;
    endcase
  endfunction
  assign _17_ = \:97 (1'h0, outputofmux2, _16_);
  fix2fp_0_15_s_5_10_f400_uid2exponentconversion_Fix2FP_H2 exponentconversion (
    .cin(1'h1),
    .clk(clk),
    .r(_30_),
    .rst(rst),
    .x(msb2signal),
    .y(valueexponent)
  );
  fix2fp_0_15_s_5_10_f400_uid2exponentfinal_Fix2FP_H2 exponentfinal (
    .cin(1'h0),
    .clk(clk),
    .r(_31_),
    .rst(rst),
    .x(partialconvertedexponentbit),
    .y(biasssignalbit)
  );
  fix2fp_0_15_s_5_10_f400_uid2_fractionconvert_Fix2FP_H2 fractionconverter (
    .cin(1'h0),
    .clk(clk),
    .r(_08_),
    .rst(rst),
    .x(tempconvert0),
    .y(tempaddsign)
  );
  fix2fp_0_15_s_5_10_f400_uid2_lzocs_Fix2FP_H2 lzoc_component (
    .clk(clk),
    .count(_00_),
    .i(input2lzoc),
    .o(_11_),
    .ozb(signsignal),
    .rst(rst)
  );
  fix2fp_0_15_s_5_10_f400_uid2_onesubstracter_Fix2FP_H2 onesubstracter (
    .cin(1'h0),
    .clk(clk),
    .r(_09_),
    .rst(rst),
    .x(fractionremainder),
    .y(minusone)
  );
  fix2fp_0_15_s_5_10_f400_uid2roundingadder_Fix2FP_H2 roundingadder (
    .cin(outputofmux1),
    .clk(clk),
    .r(_18_),
    .rst(rst),
    .x(concatenationforrounding),
    .y(possiblecorrector4rounding)
  );
  fix2fp_0_15_s_5_10_f400_uid2zerod_Fix2FP_H2 zerod (
    .cin(1'h0),
    .clk(clk),
    .r(_04_),
    .rst(rst),
    .x(passedinput),
    .y(minusone4zd)
  );
  assign \input  = I;
  assign signsignal = \input [15];
  assign signsignal_d1 = _26_;
  assign signsignal_d2 = _27_;
  assign passedinput = \input ;
  assign input2lzoc = passedinput[14:0];
  assign temporalexponent = \lzoc_component:11 ;
  assign temporalfraction = \lzoc_component:12 ;
  assign msb2signal = 5'h0e;
  assign zeropadding4exponent = 1'h0;
  assign valueexponent = _22_;
  assign partialconvertedexponent = \exponentconversion:22 ;
  assign biassofones = 4'hf;
  assign biasssignal = { 1'h0, biassofones };
  assign biasssignalbit = { 1'h0, biasssignal };
  assign partialconvertedexponentbit = { 1'h0, partialconvertedexponent };
  assign sign4ou = partialconvertedexponent[4];
  assign convertedexponentbit = \exponentfinal:34 ;
  assign convertedexponent = convertedexponentbit[4:0];
  assign underflowsignal = _34_;
  assign overflowsignal = _03_;
  assign minusone4zd = 16'hffff;
  assign zerods = \zerod:55 ;
  assign zeroinput = _06_;
  assign zeroinput_d1 = _28_;
  assign zeroinput_d2 = _29_;
  assign sign2vector = { signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2, signsignal_d2 };
  assign tempconvert = _07_;
  assign tempconvert0 = { 1'h0, tempconvert };
  assign temppaddingaddsign = 16'h0000;
  assign tempaddsign = { temppaddingaddsign, signsignal_d2 };
  assign tempfractionresult = \fractionconverter:72 ;
  assign correctingexponent = tempfractionresult[16];
  assign fractionconverted = tempfractionresult[14:5];
  assign firstbitofrest = tempfractionresult[4];
  assign lastbitoffraction = tempfractionresult[5];
  assign minusone = 4'hf;
  assign fractionremainder = tempfractionresult[3:0];
  assign zerofractionresult = \onesubstracter:82 ;
  assign zeroremainder = _13_;
  assign outputofmux3 = lastbitoffraction;
  assign outputofmux2 = _15_;
  assign outputofmux1 = _17_;
  assign possiblecorrector4rounding = { 5'h00, correctingexponent, 10'h000 };
  assign concatenationforrounding = { 1'h0, convertedexponent, fractionconverted };
  assign roundedresult = \roundingadder:105 ;
  assign convertedexponentafterrounding = roundedresult[14:10];
  assign convertedfractionafterrounding = roundedresult[9:0];
  assign msbselection = _19_;
  assign lsbselection = _23_;
  assign selection = _25_;
  assign specialbits = selection;
  assign \lzoc_component:11  = _00_;
  assign \lzoc_component:12  = _11_;
  assign \exponentconversion:22  = _30_;
  assign \exponentfinal:34  = _31_;
  assign \zerod:55  = _04_;
  assign \fractionconverter:72  = _08_;
  assign \onesubstracter:82  = _09_;
  assign \roundingadder:105  = _18_;
  assign O = { specialbits, signsignal_d2, convertedexponentafterrounding, convertedfractionafterrounding };
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_15_s_5_10_f400_uid2_fractionconvert_Fix2FP_H2(clk, rst, x, y, cin, r);
  wire [16:0] _0_;
  wire [16:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [16:0] r;
  wire [16:0] r;
  input rst;
  wire rst;
  input [16:0] x;
  wire [16:0] x;
  input [16:0] y;
  wire [16:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 16'h0000, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_15_s_5_10_f400_uid2_lzocs_Fix2FP_H2(clk, rst, i, ozb, count, o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire [14:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [14:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [14:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [14:0] _15_;
  reg _16_;
  reg _17_;
  reg _18_;
  reg _19_;
  reg [14:0] _20_;
  reg _21_;
  reg _22_;
  reg [14:0] _23_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  wire count0;
  wire count1;
  wire count1_d1;
  wire count2;
  wire count2_d1;
  wire count3;
  wire count3_d1;
  wire count3_d2;
  input [14:0] i;
  wire [14:0] i;
  wire [14:0] level0;
  wire [14:0] level1;
  wire [14:0] level1_d1;
  wire [14:0] level2;
  wire [14:0] level3;
  wire [14:0] level3_d1;
  wire [14:0] level4;
  output [15:0] o;
  wire [15:0] o;
  input ozb;
  wire ozb;
  input rst;
  wire rst;
  wire [3:0] scount;
  wire sozb;
  wire sozb_d1;
  wire sozb_d2;
  assign _00_ = level4[14:7] == { sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb };
  assign _01_ = _00_ ? 1'h1 : 1'h0;
  assign _02_ = ~ count3;
  assign _03_ = _02_ ? level4 : { level4[6:0], 8'h00 };
  assign _04_ = level3_d1[14:11] == { sozb_d1, sozb_d1, sozb_d1, sozb_d1 };
  assign _05_ = _04_ ? 1'h1 : 1'h0;
  assign _06_ = ~ count2;
  assign _07_ = _06_ ? level3_d1 : { level3_d1[10:0], 4'h0 };
  assign _08_ = level2[14:13] == { sozb_d1, sozb_d1 };
  assign _09_ = _08_ ? 1'h1 : 1'h0;
  assign _10_ = ~ count1;
  assign _11_ = _10_ ? level2 : { level2[12:0], 2'h0 };
  assign _12_ = level1_d1[14] == sozb_d2;
  assign _13_ = _12_ ? 1'h1 : 1'h0;
  assign _14_ = ~ count0;
  assign _15_ = _14_ ? level1_d1 : { level1_d1[13:0], 1'h0 };
  always @(posedge clk)
    _16_ <= sozb;
  always @(posedge clk)
    _17_ <= sozb_d1;
  always @(posedge clk)
    _18_ <= count3;
  always @(posedge clk)
    _19_ <= count3_d1;
  always @(posedge clk)
    _20_ <= level3;
  always @(posedge clk)
    _21_ <= count2;
  always @(posedge clk)
    _22_ <= count1;
  always @(posedge clk)
    _23_ <= level1;
  assign level4 = i;
  assign sozb = ozb;
  assign sozb_d1 = _16_;
  assign sozb_d2 = _17_;
  assign count3 = _01_;
  assign count3_d1 = _18_;
  assign count3_d2 = _19_;
  assign level3 = _03_;
  assign level3_d1 = _20_;
  assign count2 = _05_;
  assign count2_d1 = _21_;
  assign level2 = _07_;
  assign count1 = _09_;
  assign count1_d1 = _22_;
  assign level1 = _11_;
  assign level1_d1 = _23_;
  assign count0 = _13_;
  assign level0 = _15_;
  assign scount = { count3_d2, count2_d1, count1_d1, count0 };
  assign count = scount;
  assign o = { level0, 1'h0 };
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_15_s_5_10_f400_uid2_onesubstracter_Fix2FP_H2(clk, rst, x, y, cin, r);
  wire [3:0] _0_;
  wire [3:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [3:0] r;
  wire [3:0] r;
  input rst;
  wire rst;
  input [3:0] x;
  wire [3:0] x;
  input [3:0] y;
  wire [3:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 3'h0, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_15_s_5_10_f400_uid2exponentconversion_Fix2FP_H2(clk, rst, x, y, cin, r);
  wire [4:0] _0_;
  wire [4:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [4:0] r;
  wire [4:0] r;
  input rst;
  wire rst;
  input [4:0] x;
  wire [4:0] x;
  input [4:0] y;
  wire [4:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 4'h0, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_15_s_5_10_f400_uid2exponentfinal_Fix2FP_H2(clk, rst, x, y, cin, r);
  wire [5:0] _0_;
  wire [5:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [5:0] r;
  wire [5:0] r;
  input rst;
  wire rst;
  input [5:0] x;
  wire [5:0] x;
  input [5:0] y;
  wire [5:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 5'h00, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_15_s_5_10_f400_uid2roundingadder_Fix2FP_H2(clk, rst, x, y, cin, r);
  wire [15:0] _0_;
  wire [15:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [15:0] r;
  wire [15:0] r;
  input rst;
  wire rst;
  input [15:0] x;
  wire [15:0] x;
  input [15:0] y;
  wire [15:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 15'h0000, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_15_s_5_10_f400_uid2zerod_Fix2FP_H2(clk, rst, x, y, cin, r);
  wire [15:0] _0_;
  wire [15:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [15:0] r;
  wire [15:0] r;
  input rst;
  wire rst;
  input [15:0] x;
  wire [15:0] x;
  input [15:0] y;
  wire [15:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 15'h0000, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/
