/* Generated by Yosys 0.53 (git sha1 53c22ab7c, ccache clang++ 18.1.3 -fPIC -O3) */

(* top =  1  *)
/* verilator lint_off CASEOVERLAP*/
module Fix2FP_S1(clk, rst, I, O);
  wire [4:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [31:0] _04_;
  wire _05_;
  wire _06_;
  wire [31:0] _07_;
  wire [32:0] _08_;
  wire [6:0] _09_;
  wire _10_;
  wire [31:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire [31:0] _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire [7:0] _22_;
  wire _23_;
  wire _24_;
  wire [1:0] _25_;
  reg _26_;
  reg _27_;
  wire [7:0] _28_;
  wire [8:0] _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  input [31:0] I;
  wire [31:0] I;
  output [33:0] O;
  wire [33:0] O;
  wire [6:0] biassofones;
  wire [7:0] biasssignal;
  wire [8:0] biasssignalbit;
  input clk;
  wire clk;
  wire [31:0] concatenationforrounding;
  wire [7:0] convertedexponent;
  wire [7:0] convertedexponentafterrounding;
  wire [8:0] convertedexponentbit;
  wire [22:0] convertedfractionafterrounding;
  wire correctingexponent;
  wire [7:0] \exponentconversion:20 ;
  wire [8:0] \exponentfinal:32 ;
  wire firstbitofrest;
  wire [22:0] fractionconverted;
  wire [32:0] \fractionconverter:76 ;
  wire [6:0] fractionremainder;
  wire [31:0] \input ;
  wire [30:0] input2lzoc;
  wire lastbitoffraction;
  wire lsbselection;
  wire [31:0] \lzoc_component:10 ;
  wire [4:0] \lzoc_component:9 ;
  wire [6:0] minusone;
  wire [31:0] minusone4zd;
  wire [7:0] msb2signal;
  wire msbselection;
  wire [6:0] \onesubstracter:86 ;
  wire outputofmux1;
  wire outputofmux2;
  wire outputofmux3;
  wire overflowsignal;
  wire [7:0] partialconvertedexponent;
  wire [8:0] partialconvertedexponentbit;
  wire [31:0] passedinput;
  wire [31:0] possiblecorrector4rounding;
  wire [31:0] roundedresult;
  wire [31:0] \roundingadder:109 ;
  input rst;
  wire rst;
  wire [1:0] selection;
  wire [31:0] sign2vector;
  wire sign4ou;
  wire signsignal;
  wire signsignal_d1;
  wire [1:0] specialbits;
  wire [32:0] tempaddsign;
  wire [31:0] tempconvert;
  wire [32:0] tempconvert0;
  wire [32:0] tempfractionresult;
  wire [4:0] temporalexponent;
  wire [31:0] temporalfraction;
  wire [31:0] temppaddingaddsign;
  wire underflowsignal;
  wire [7:0] valueexponent;
  wire [31:0] \zerod:53 ;
  wire [31:0] zerods;
  wire [6:0] zerofractionresult;
  wire zeroinput;
  wire zeroinput_d1;
  wire [2:0] zeropadding4exponent;
  wire zeroremainder;
  function [0:0] \:101 ;
    input [0:0] a;
    input [0:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:101  = b[0:0];
      default:
        \:101  = a;
    endcase
  endfunction
  assign _17_ = \:101 (1'h0, outputofmux2, _16_);
  assign _19_ = overflowsignal | roundedresult[31];
  assign _20_ = ~ zeroinput_d1;
  assign _21_ = underflowsignal & _20_;
  assign _23_ = ~ _21_;
  assign _24_ = ~ zeroinput_d1;
  assign _25_ = _24_ ? { msbselection, lsbselection } : 2'h0;
  always @(posedge clk)
    _26_ <= signsignal;
  always @(posedge clk)
    _27_ <= zeroinput;
  assign _22_ = ~ { zeropadding4exponent, temporalexponent };
  assign _30_ = convertedexponentbit[8:7] == 2'h1;
  assign _31_ = _30_ & sign4ou;
  assign _32_ = _31_ ? 1'h1 : 1'h0;
  assign _33_ = ~ sign4ou;
  assign _01_ = convertedexponentbit[8:7] == 2'h2;
  assign _02_ = _01_ & _33_;
  assign _03_ = _02_ ? 1'h1 : 1'h0;
  assign _05_ = ~ signsignal;
  assign _06_ = zerods[31] & _05_;
  assign _07_ = sign2vector ^ temporalfraction;
  assign _10_ = ~ tempfractionresult[6];
  assign _12_ = _10_ & zerofractionresult[6];
  assign _13_ = ~ _12_;
  assign _14_ = zeroremainder == 1'h0;
  function [0:0] \:97 ;
    input [0:0] a;
    input [0:0] b;
    input [0:0] s;
    (* parallel_case *)
    casez (s)
      1'b1:
        \:97  = b[0:0];
      default:
        \:97  = a;
    endcase
  endfunction
  assign _15_ = \:97 (1'h1, outputofmux3, _14_);
  assign _16_ = firstbitofrest == 1'h1;
  fix2fp_0_31_s_8_23_f250_uid2exponentconversion_Fix2FP_S1 exponentconversion (
    .cin(1'h1),
    .clk(clk),
    .r(_28_),
    .rst(rst),
    .x(msb2signal),
    .y(valueexponent)
  );
  fix2fp_0_31_s_8_23_f250_uid2exponentfinal_Fix2FP_S1 exponentfinal (
    .cin(1'h0),
    .clk(clk),
    .r(_29_),
    .rst(rst),
    .x(partialconvertedexponentbit),
    .y(biasssignalbit)
  );
  fix2fp_0_31_s_8_23_f250_uid2_fractionconvert_Fix2FP_S1 fractionconverter (
    .cin(1'h0),
    .clk(clk),
    .r(_08_),
    .rst(rst),
    .x(tempconvert0),
    .y(tempaddsign)
  );
  fix2fp_0_31_s_8_23_f250_uid2_lzocs_Fix2FP_S1 lzoc_component (
    .clk(clk),
    .count(_00_),
    .i(input2lzoc),
    .o(_11_),
    .ozb(signsignal),
    .rst(rst)
  );
  fix2fp_0_31_s_8_23_f250_uid2_onesubstracter_Fix2FP_S1 onesubstracter (
    .cin(1'h0),
    .clk(clk),
    .r(_09_),
    .rst(rst),
    .x(fractionremainder),
    .y(minusone)
  );
  fix2fp_0_31_s_8_23_f250_uid2roundingadder_Fix2FP_S1 roundingadder (
    .cin(outputofmux1),
    .clk(clk),
    .r(_18_),
    .rst(rst),
    .x(concatenationforrounding),
    .y(possiblecorrector4rounding)
  );
  fix2fp_0_31_s_8_23_f250_uid2zerod_Fix2FP_S1 zerod (
    .cin(1'h0),
    .clk(clk),
    .r(_04_),
    .rst(rst),
    .x(passedinput),
    .y(minusone4zd)
  );
  assign \input  = I;
  assign signsignal = \input [31];
  assign signsignal_d1 = _26_;
  assign passedinput = \input ;
  assign input2lzoc = passedinput[30:0];
  assign temporalexponent = \lzoc_component:9 ;
  assign temporalfraction = \lzoc_component:10 ;
  assign msb2signal = 8'h1e;
  assign zeropadding4exponent = 3'h0;
  assign valueexponent = _22_;
  assign partialconvertedexponent = \exponentconversion:20 ;
  assign biassofones = 7'h7f;
  assign biasssignal = { 1'h0, biassofones };
  assign biasssignalbit = { 1'h0, biasssignal };
  assign partialconvertedexponentbit = { 1'h0, partialconvertedexponent };
  assign sign4ou = partialconvertedexponent[7];
  assign convertedexponentbit = \exponentfinal:32 ;
  assign convertedexponent = convertedexponentbit[7:0];
  assign underflowsignal = _32_;
  assign overflowsignal = _03_;
  assign minusone4zd = 32'd4294967295;
  assign zerods = \zerod:53 ;
  assign zeroinput = _06_;
  assign zeroinput_d1 = _27_;
  assign sign2vector = { signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1, signsignal_d1 };
  assign tempconvert = _07_;
  assign tempconvert0 = { 1'h0, tempconvert };
  assign temppaddingaddsign = 32'd0;
  assign tempaddsign = { temppaddingaddsign, signsignal_d1 };
  assign tempfractionresult = \fractionconverter:76 ;
  assign correctingexponent = tempfractionresult[32];
  assign fractionconverted = tempfractionresult[30:8];
  assign firstbitofrest = tempfractionresult[7];
  assign lastbitoffraction = tempfractionresult[8];
  assign minusone = 7'h7f;
  assign fractionremainder = tempfractionresult[6:0];
  assign zerofractionresult = \onesubstracter:86 ;
  assign zeroremainder = _13_;
  assign outputofmux3 = lastbitoffraction;
  assign outputofmux2 = _15_;
  assign outputofmux1 = _17_;
  assign possiblecorrector4rounding = { 8'h00, correctingexponent, 23'h000000 };
  assign concatenationforrounding = { 1'h0, convertedexponent, fractionconverted };
  assign roundedresult = \roundingadder:109 ;
  assign convertedexponentafterrounding = roundedresult[30:23];
  assign convertedfractionafterrounding = roundedresult[22:0];
  assign msbselection = _19_;
  assign lsbselection = _23_;
  assign selection = _25_;
  assign specialbits = selection;
  assign \lzoc_component:9  = _00_;
  assign \lzoc_component:10  = _11_;
  assign \exponentconversion:20  = _28_;
  assign \exponentfinal:32  = _29_;
  assign \zerod:53  = _04_;
  assign \fractionconverter:76  = _08_;
  assign \onesubstracter:86  = _09_;
  assign \roundingadder:109  = _18_;
  assign O = { specialbits, signsignal_d1, convertedexponentafterrounding, convertedfractionafterrounding };
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_31_s_8_23_f250_uid2_fractionconvert_Fix2FP_S1(clk, rst, x, y, cin, r);
  wire [32:0] _0_;
  wire [32:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [32:0] r;
  wire [32:0] r;
  input rst;
  wire rst;
  input [32:0] x;
  wire [32:0] x;
  input [32:0] y;
  wire [32:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 32'h00000000, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_31_s_8_23_f250_uid2_lzocs_Fix2FP_S1(clk, rst, i, ozb, count, o);
  wire _00_;
  wire _01_;
  wire _02_;
  wire [30:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [30:0] _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire [30:0] _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [30:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire [30:0] _19_;
  reg _20_;
  reg _21_;
  reg _22_;
  reg [30:0] _23_;
  input clk;
  wire clk;
  output [4:0] count;
  wire [4:0] count;
  wire count0;
  wire count1;
  wire count2;
  wire count3;
  wire count3_d1;
  wire count4;
  wire count4_d1;
  input [30:0] i;
  wire [30:0] i;
  wire [30:0] level0;
  wire [30:0] level1;
  wire [30:0] level2;
  wire [30:0] level3;
  wire [30:0] level3_d1;
  wire [30:0] level4;
  wire [30:0] level5;
  output [31:0] o;
  wire [31:0] o;
  input ozb;
  wire ozb;
  input rst;
  wire rst;
  wire [4:0] scount;
  wire sozb;
  wire sozb_d1;
  assign _00_ = level5[30:15] == { sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb };
  assign _01_ = _00_ ? 1'h1 : 1'h0;
  assign _02_ = ~ count4;
  assign _03_ = _02_ ? level5 : { level5[14:0], 16'h0000 };
  assign _04_ = level4[30:23] == { sozb, sozb, sozb, sozb, sozb, sozb, sozb, sozb };
  assign _05_ = _04_ ? 1'h1 : 1'h0;
  assign _06_ = ~ count3;
  assign _07_ = _06_ ? level4 : { level4[22:0], 8'h00 };
  assign _08_ = level3_d1[30:27] == { sozb_d1, sozb_d1, sozb_d1, sozb_d1 };
  assign _09_ = _08_ ? 1'h1 : 1'h0;
  assign _10_ = ~ count2;
  assign _11_ = _10_ ? level3_d1 : { level3_d1[26:0], 4'h0 };
  assign _12_ = level2[30:29] == { sozb_d1, sozb_d1 };
  assign _13_ = _12_ ? 1'h1 : 1'h0;
  assign _14_ = ~ count1;
  assign _15_ = _14_ ? level2 : { level2[28:0], 2'h0 };
  assign _16_ = level1[30] == sozb_d1;
  assign _17_ = _16_ ? 1'h1 : 1'h0;
  assign _18_ = ~ count0;
  assign _19_ = _18_ ? level1 : { level1[29:0], 1'h0 };
  always @(posedge clk)
    _20_ <= sozb;
  always @(posedge clk)
    _21_ <= count4;
  always @(posedge clk)
    _22_ <= count3;
  always @(posedge clk)
    _23_ <= level3;
  assign level5 = i;
  assign sozb = ozb;
  assign sozb_d1 = _20_;
  assign count4 = _01_;
  assign count4_d1 = _21_;
  assign level4 = _03_;
  assign count3 = _05_;
  assign count3_d1 = _22_;
  assign level3 = _07_;
  assign level3_d1 = _23_;
  assign count2 = _09_;
  assign level2 = _11_;
  assign count1 = _13_;
  assign level1 = _15_;
  assign count0 = _17_;
  assign level0 = _19_;
  assign scount = { count4_d1, count3_d1, count2, count1, count0 };
  assign count = scount;
  assign o = { level0, 1'h0 };
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_31_s_8_23_f250_uid2_onesubstracter_Fix2FP_S1(clk, rst, x, y, cin, r);
  wire [6:0] _0_;
  wire [6:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [6:0] r;
  wire [6:0] r;
  input rst;
  wire rst;
  input [6:0] x;
  wire [6:0] x;
  input [6:0] y;
  wire [6:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 6'h00, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_31_s_8_23_f250_uid2exponentconversion_Fix2FP_S1(clk, rst, x, y, cin, r);
  wire [7:0] _0_;
  wire [7:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [7:0] r;
  wire [7:0] r;
  input rst;
  wire rst;
  input [7:0] x;
  wire [7:0] x;
  input [7:0] y;
  wire [7:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 7'h00, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_31_s_8_23_f250_uid2exponentfinal_Fix2FP_S1(clk, rst, x, y, cin, r);
  wire [8:0] _0_;
  wire [8:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [8:0] r;
  wire [8:0] r;
  input rst;
  wire rst;
  input [8:0] x;
  wire [8:0] x;
  input [8:0] y;
  wire [8:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 8'h00, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_31_s_8_23_f250_uid2roundingadder_Fix2FP_S1(clk, rst, x, y, cin, r);
  wire [31:0] _0_;
  wire [31:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [31:0] r;
  wire [31:0] r;
  input rst;
  wire rst;
  input [31:0] x;
  wire [31:0] x;
  input [31:0] y;
  wire [31:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 31'h00000000, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/

/* verilator lint_off CASEOVERLAP*/
module fix2fp_0_31_s_8_23_f250_uid2zerod_Fix2FP_S1(clk, rst, x, y, cin, r);
  wire [31:0] _0_;
  wire [31:0] _1_;
  input cin;
  wire cin;
  input clk;
  wire clk;
  output [31:0] r;
  wire [31:0] r;
  input rst;
  wire rst;
  input [31:0] x;
  wire [31:0] x;
  input [31:0] y;
  wire [31:0] y;
  assign _0_ = x + y;
  assign _1_ = _0_ + { 31'h00000000, cin };
  assign r = _1_;
endmodule
/* verilator lint_on CASEOVERLAP*/
